runtime: go111  # or go112 for the Go 1.12 runtime

includes:
- secret.yaml

handlers:
- url: /static
  static_dir: static

- url: /templates
  static_dir: templates

- url: /.*
  script: auto
  secure: always
